# Generated by Django 5.2.7 on 2025-10-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('studentID', models.CharField(max_length=8)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=100)),
                ('hobbies', models.TextField()),
                ('future_goals', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Learning_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completion_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lwJourney.student')),
            ],
        ),
    ]
